apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
stringData:
  NODE_ENV: {{ .Values.env.NODE_ENV | default "production" | quote }}
  PORT: {{ .Values.env.PORT | default "3000" | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.env.NEXT_PUBLIC_API_URL | quote }}
